
NAME = rush-02

SRCS = (mainfile, atoi.c, main.c,...)

OBJS = {SOURCES:.c=.o)

FLAGS = -Wall -Werror -Wextra

${NAME}: ${OBJS}
	cc -o ${NAME} ${SRCS}

clean:
		rm -f ${OBJS}

fclean: clean
		rm -f ${NAME}
